@MiApp_API_HostAddress = http://localhost:5150

### Login correcto
POST {{MiApp_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Login incorrecto
POST {{MiApp_API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "999"
}